Repository googleapis/nodejs-rcloadenv, pull requests merged in 2019-06, with the labels that each got.

#87 feat: support apiEndpoint override
  package.json
  src/index.ts
  test/index.ts
Labels: cla: yes

#89 chore: release 1.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#90 build: remove unused clang format
  .clang-format
  src/index.ts
Labels: automerge, cla: yes

#91 docs: add repo-metadata file to generate docs
  .repo-metadata.json
  synth.py
Labels: cla: yes

#92 build: switch to GitHub magic proxy, for release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#93 fix(docs): link to reference docs section on googleapis.dev
  .jsdoc.js
Labels: cla: yes

#94 chore: release 1.1.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#95 build: use config file for linkinator
  linkinator.config.json
  package.json
Labels: cla: yes
