Repository googleapis/nodejs-rcloadenv, pull requests merged in 2020-07, with the labels that each got.

#185 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#186 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#188 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#191 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  synth.metadata
Labels: automerge, cla: yes, context: none

#192 build: missing closing paren in publish script, delete template for Node 8, add config files for cloud-rad
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#193 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#194 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#195 build: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#196 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full
